name: Deploy de arquivo no s3

on:
  push:
    branches:
      - main
      
jobs:
  upload:
    runs-on: ubuntu-latest


    steps:
      - name: checkout do repositorio
        uses: actions/checkout@v4

      - name: Enviar arquivo para o s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws s3 cp upload/ s3://projetoci/ --recursive
